### ISSUE TITLE
A user can see the number of days before the deadline and the number of days that have passed the deadline

### ISSUE THREAD

**Issue by FineThxAndU** [cs2103jan2015-t17-1c/main#3]
so that he can keep track of the tasks and arrange time accordingly

**Comment by wangjiexuan** [comment]
so that

**Comment by jhyapril** [comment]
what do you mean by number of days have passed the deadlines.

**Comment by FineThxAndU** [comment]
@jhyapril That's what you wrote!

**Comment by jhyapril** [comment]
@wangjiexuan  No! btw why do we care about the days have passed the dealines?

**Comment by FineThxAndU** [comment]
i dun know ....@jhyapril ask @xumeng0621

**Comment by xumeng0621** [comment]
it means how many days ago before it happened
